# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dolbomi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dolbomi

pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'
pod 'Kingfisher'
pod 'Moya'
pod 'SnapKit'
pod 'RxViewController'
pod 'Then'
pod 'RxAlamofire'
pod 'Pure'
pod 'DLRadioButton'

end
